package com.focuson.app.domain.model

import androidx.compose.ui.graphics.Color

enum class PresetMode(
    val id: String,
    val displayNameRes: Int,
    val taglineRes: Int,
    val color: Color,
    val defaultAppPackages: List<String>,
    val defaultSitePatterns: List<String>,
    val defaultDurationMin: Int,
    val strictByDefault: Boolean,
    val whitelistMode: Boolean,
) {
    STUDENT(
        id = "student",
        displayNameRes = com.focuson.app.R.string.preset_student_name,
        taglineRes = com.focuson.app.R.string.preset_student_tagline,
        color = Color(0xFF3D5AF1),
        defaultAppPackages = listOf(
            "com.instagram.android",
            "com.zhiliaoapp.musically",          // TikTok
            "com.twitter.android",
            "com.facebook.katana",
            "com.google.android.youtube",
            "com.google.android.apps.youtube.music",
            "com.nhn.android.webtoon",
            "com.naver.webtoon",
            "com.kakao.page",
            "com.kakao.piccoma",
            "com.coupang.mobile",
            "com.ebay.kr.gmarket",
            "com.elevenst",
            "kr.co.nowcom.mobile.afreeca",
            "com.netflix.mediaclient",
            "net.cj.cjhv.gs.tving",
            "com.coupang.coupangplay",
            "com.disney.disneyplus",
            "com.dcinside.app.android",
            "com.ppomppu.android",
        ),
        defaultSitePatterns = listOf(
            "*.youtube.com",
            "youtu.be",
            "*.instagram.com",
            "*.tiktok.com",
            "*.twitter.com",
            "*.x.com",
            "*.facebook.com",
            "*.namu.wiki",
            "comic.naver.com",
            "m.comic.naver.com",
            "*.dcinside.com",
            "*.ppomppu.co.kr",
            "*.netflix.com",
            "*.twitch.tv",
            "*.reddit.com",
        ),
        defaultDurationMin = 120,
        strictByDefault = false,
        whitelistMode = false,
    ),
    WORKER(
        id = "worker",
        displayNameRes = com.focuson.app.R.string.preset_worker_name,
        taglineRes = com.focuson.app.R.string.preset_worker_tagline,
        color = Color(0xFF0EA371),
        defaultAppPackages = listOf(
            "com.instagram.android",
            "com.zhiliaoapp.musically",
            "com.google.android.youtube",
            "com.netflix.mediaclient",
            "net.cj.cjhv.gs.tving",
            "com.coupang.coupangplay",
            "com.disney.disneyplus",
            "com.dcinside.app.android",
            "com.ppomppu.android",
            "kr.co.nowcom.mobile.afreeca",
            "com.twitter.android",
            "com.facebook.katana",
        ),
        defaultSitePatterns = listOf(
            "*.instagram.com",
            "*.youtube.com",
            "*.tiktok.com",
            "*.dcinside.com",
            "*.ppomppu.co.kr",
            "*.netflix.com",
            "*.twitch.tv",
            "*.reddit.com",
        ),
        defaultDurationMin = 240,
        strictByDefault = false,
        whitelistMode = false,
    ),
    MEDITATION(
        id = "meditation",
        displayNameRes = com.focuson.app.R.string.preset_meditation_name,
        taglineRes = com.focuson.app.R.string.preset_meditation_tagline,
        color = Color(0xFFB341FF),
        defaultAppPackages = listOf(
            "com.android.dialer",
            "com.google.android.dialer",
            "com.samsung.android.dialer",
            "com.android.deskclock",
            "com.google.android.deskclock",
            "com.sec.android.app.clockpackage",
            "com.focuson.app",
            "com.focuson.app.debug",
        ),
        defaultSitePatterns = emptyList(),
        defaultDurationMin = 20,
        strictByDefault = true,
        whitelistMode = true,
    );

    companion object {
        fun fromId(id: String): PresetMode? = entries.firstOrNull { it.id == id }
    }
}
